version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:5000"
    environment:
      # TO-DO: Change these if using in production
      FLASK_ENV: development
      FLASK_APP: ./api/app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/api
    env_file: .env

  postgres:
    image: postgres
    restart: always
    environment:
      # TO-DO: Change these if using in production
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres